version: '3'
services:
  analyze:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /home/node/app/node_modules
      - ./:/home/node/app
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
