version: '3'
services:
  analyze:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /home/node/app/node_modules
      - ./:/home/node/app
    ports:
      - '8000:8000'
